apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 4000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: appointment-mvp-backend:latest
        env:
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "postgres"
        - name: DATABASE_NAME
          value: "my_appointments_db"
        ports:
        - containerPort: 4000
