version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_appointments_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./back/docker-entrypoint-initdb.d

  backend:
    container_name: backend
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - /usr/src/app/node_modules
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./front/my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
volumes:
  pgdata:
